db:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: mysecretpassword
  driver: org.postgresql.Driver

server:
  error:
    include-message: always
    include-stacktrace: always

