server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: customer-ms
          uri: http://localhost:8081/
          predicates:
            - Path=/customer-app/**
        - id: order-ms
          uri: http://localhost:8082/
          predicates:
            - Path=/order-app/**
        - id: products-ms
          uri: http://localhost:8083/
          predicates:
            - Path=/product-app/**