package az.atlacademy.module03.lesson81;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class HashingMd5 {
    public static String getMd5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
// Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);
// Convert message digest into hex value
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
// For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }

    }

    public static void main(String args[]) throws NoSuchAlgorithmException {
        String s = "ATLACADEMY";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
    }

}
